spring:
  application:
    name: 'order service'
    boot:
      client: http://localhost:8081
datasource:
  url: jdbc:h2:mem:order
  username: sa
  password:
  driver-class-name: org.h2.Driver
  plataform: h2
server:
  port: 8082

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS